@startuml
entity "users" {
    + user_id [PK]
    ==
    name
    weight
}



entity "events" {
    + event_id [PK]
    ==
    #user_id
    partcode
    date
    memo
}



entity "event_stage" {
    + seq [PK]
    ==
    #event_id
    #stage_id
}

entity "trainings" {
    + training_id [PK]
    ==
    weight
    rep
    is_max
}

entity "stage_user" {
    + seq [PK]
    ==
    #stage_id
    #user_id
    sort_no
}


entity "stages" {
    + stage_id [PK]
    ==
    name
    part_code
    pof_code
    memo
}


users --o{ events
events --o{ event_stage
event_stage --o{ trainings
users --o{ stage_user
stage_user --o{ stages
stages --o{ event_stage
@enduml